# Generated by Django 2.0.1 on 2020-05-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ranking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
